**VIT AI Assignment 1 
Ronodeep Das 20BCE1866
ronodeep.das2020@vitstudent.ac.in**

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
#Task 1
ar=np.random.rand(4,4)
df=pd.DataFrame(ar)
df

          0         1         2         3
0  0.186061  0.223340  0.733085  0.736616
1  0.262811  0.931660  0.015598  0.417365
2  0.222934  0.590852  0.257479  0.472450
3  0.749635  0.071234  0.445404  0.266412

In [ ]:
#Task 2
df.columns=['Random Value 1','Random Value 2','Random Value 3','Random Value 4']
df

   Random Value 1  Random Value 2  Random Value 3  Random Value 4
0        0.186061        0.223340        0.733085        0.736616
1        0.262811        0.931660        0.015598        0.417365
2        0.222934        0.590852        0.257479        0.472450
3        0.749635        0.071234        0.445404        0.266412

In [ ]:
#Task 3
print(df.describe())
print(df.sum())

       Random Value 1  Random Value 2  Random Value 3  Random Value 4
count        4.000000        4.000000        4.000000        4.000000
mean         0.355360        0.454272        0.362891        0.473211
std          0.264712        0.385833        0.303082        0.196017
min          0.186061        0.071234        0.015598        0.266412
25%          0.213715        0.185314        0.197009        0.379627
50%          0.242872        0.407096        0.351441        0.444908
75%          0.384517        0.676054        0.517324        0.538492
max          0.749635        0.931660        0.733085        0.736616
Random Value 1    1.421440
Random Value 2    1.817087
Random Value 3    1.451566
Random Value 4    1.892843
dtype: float64

In [ ]:
#Task 4
print(df.isnull())
dt=df.dtypes
print(dt)

   Random Value 1  Random Value 2  Random Value 3  Random Value 4
0           False           False           False           False
1           False           False           False           False
2           False           False           False           False
3           False           False           False           False
Random Value 1    float64
Random Value 2    float64
Random Value 3    float64
Random Value 4    float64
dtype: object

In [ ]:
#Task 5
print(df.loc['0':'3', 'Random Value 2'])
print(df.loc['0':'3', 'Random Value 3'])
df.iloc[0:4,[1,2]]

0    0.223340
1    0.931660
2    0.590852
3    0.071234
Name: Random Value 2, dtype: float64
0    0.733085
1    0.015598
2    0.257479
3    0.445404
Name: Random Value 3, dtype: float64

   Random Value 2  Random Value 3
0        0.223340        0.733085
1        0.931660        0.015598
2        0.590852        0.257479
3        0.071234        0.445404